name: Backend - Functional Tests
description: Run Functional Tests for backend
inputs:
  NPM_TOKEN:
    description: Github token for package registry authentication
    required: true
runs:
  using: "composite"
  steps:
    - name: Run backend functional test
      shell: bash
      run: |
        cd backend
        docker-compose -f ./features/docker-compose.yml up -d
        bash features/wait-kuzzle.sh
        npm run test:functional
      env:
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
