name: Deploy

on:
  push:
    branches:
      - production
env:
  PAAS_ENV: production
  PAAS_PROJECT: geodis-sdl

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: "14"
      - name: Set Github package registry
        run: npm config set @kuzzleio:registry https://packages.paas.kuzzle.io
      - name: Github package registry authentication
        run: npm set //packages.paas.kuzzle.io/:_authToken ${{ secrets.NPM_TOKEN }}
      - uses: ./.github/actions/backend-lint

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-18.04
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: ./.github/actions/backend-functional-test
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  push_backend:
    name: backend artefact
    runs-on: ubuntu-18.04
    needs: [functional-tests]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: harbor.paas.kuzzle.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          file: ./backend/Dockerfile
          context: ./backend
          push: true
          tags: harbor.paas.kuzzle.io/${{ env.PAAS_PROJECT }}/${{ env.PAAS_ENV }}/kuzzle:${{ steps.vars.outputs.sha_short }}

  deploy_backend:
    name: Deploy backend artefact
    runs-on: ubuntu-18.04
    needs: [push_backend]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get current commit short SHA
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: "14"
      - name: Deploy paas
        run: |
          cd backend
          npm install -g kourou
          export KUZZLE_PAAS_PASSWORD="${{ secrets.REGISTRY_PASSWORD }}"
          kourou paas:login --username="${{ secrets.REGISTRY_USERNAME }}"
          kourou paas:deploy ${{ env.PAAS_ENV }} harbor.paas.kuzzle.io/${{ env.PAAS_PROJECT }}/${{ env.PAAS_ENV }}/kuzzle:${{ steps.vars.outputs.sha_short }}
